services:
  mysql:
    image: mysql:8.0.29
    container_name: cvc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_cvc_case
      MYSQL_USER: cvccase
      MYSQL_PASSWORD: cvccase
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - cvc-network

  # rest_api:
  #   container_name: cvc_customers_api
  #   build:
  #     context: ../
  #     dockerfile: Dockerfile
  #   environment:
  #     TZ: "America/Sao_Paulo"
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_cvc_case?useTimezone=true&serverTimezone=UTC
  #     SPRING_DATASOURCE_USERNAME: cvccase
  #     SPRING_DATASOURCE_PASSWORD: cvccase
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - mysql
  #   networks:
  #     - cvc-network

networks:
  cvc-network:
    driver: bridge